### ISSUE TITLE
How does search for podcasts work?

### ISSUE THREAD

**Issue by chraibi** [pozapas/EvacuAIPod#1]
It seems, that many search requests 'cognitive map' I get mainly results from the Fire Science Show.

<img width="828" alt="Screenshot 2024-06-10 at 18 55 25" src="https://github.com/pozapas/EvacuAIPod/assets/5772973/26e60369-8a0e-4c4f-b70f-b80c3cadd87b">

I'm not sure this is the write answer, but can it be you search only in the Fire Science Show?

**Comment by pozapas** [comment]
Thank you for your feedback. Currently, our podcast searches are limited to "Fire Science Show" and "The Uncovered Witness: Fire Science Revelations," and for YouTube, we feature "HBiF IAFSS" webinars. This is why your search for 'cognitive map' may seem restricted. Our News section does offer an open search feature for broader results. 

We are working on expanding our content coverage to include more sources related to crowd evacuation and fire engineering. Let us know if you have any suggestions for podcasts, webinars, or other content that we can add to the database.

**Comment by chraibi** [comment]
Ok, good to know. Thanks!
