### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by chraibi** [pozapas/EvacuAIPod#3]
Do you really require both packages `faiss-cpu` and `faiss-gpu`?
I ask this because install `faiss-gpu` is a hassle and apparently not supported on my machine. 
<img width="1247" alt="Screenshot 2024-06-12 at 09 11 11" src="https://github.com/pozapas/EvacuAIPod/assets/5772973/8755da47-3e8d-41d3-ab77-d2d6e28a026a">

**Comment by pozapas** [comment]
As `faiss-gpu` is not supported correctly in the local version, I have updated the requirements file to address this issue. I recommend using `faiss-cpu` for local installations to ensure compatibility and ease of setup.
