### ISSUE TITLE
Secrets are missing

### ISSUE THREAD

**Issue by chraibi** [pozapas/EvacuAIPod#4]
I think in readme you need to explain how to change this part:
<img width="510" alt="Screenshot 2024-06-12 at 09 12 49" src="https://github.com/pozapas/EvacuAIPod/assets/5772973/5639c9e2-4ae2-4112-a0c1-d323945804a6">

Otherwise, this will happen:

<img width="622" alt="Screenshot 2024-06-12 at 09 11 48" src="https://github.com/pozapas/EvacuAIPod/assets/5772973/81f98923-8b4d-415e-8fa3-717768f067e3">

**Comment by pozapas** [comment]
The README file has been updated.
